name: Teknotok Takip

on:
  schedule:
    - cron: '0 */2 * * *' # 2 saatte bir çalışır
  workflow_dispatch: # El ile başlatma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu kopyala
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Kur
        run: pip install requests lxml

      - name: Takip Kodunu Calistir
        run: python takip.py

      - name: Hafizayi Guncelle ve Kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add urun_takip_hafiza.json
          git commit -m "Hafiza guncellendi: $(date)" || echo "Degisiklik yok"
          git push
